In [3]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Laptop GPU


In [2]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [3]:
# Add and reassign
tensor = tensor + 10
tensor + 10, tensor * 10            

(tensor([21, 22, 23]), tensor([110, 120, 130]))

`tensor` returns a tensor , `tensor * 10` returns a tensor, but the both are assigned back into tensor variable as a tuple

It calculates tensor (which results in a tensor).
It calculates tensor * 10 (which also results in a tensor).
It then combines the results of these two calculations into a tuple (result_of_add, result_of_multiply).
Finally, it assigns this tuple back to the variable tensor.

In [4]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [5]:
print(tensor, "*", tensor)
print("Equals", tensor * tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals tensor([121, 144, 169])


In [6]:
tensor

tensor([11, 12, 13])

In [7]:
demo_tensor =  torch.tensor([[1,2,3,4], [5,6,7,8]])
demo_tensor.shape

torch.Size([2, 4])

In [8]:
torch.matmul(tensor, tensor)

tensor(434)

In [9]:
tensor.matmul(tensor)

tensor(434)

In [10]:
tensor @ tensor

tensor(434)

In [11]:
tensor_A = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_B = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_C = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(tensor_A.shape)
print(tensor_B.shape)
print(tensor_C.shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])


In [12]:
tensor_B.T ,tensor_B


(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [13]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [14]:
tensor_A.mm(tensor_B.T)

tensor([[14, 32],
        [32, 77]])

In [15]:
torch.mm(tensor_A, tensor_B.T)

tensor([[14, 32],
        [32, 77]])

In [36]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [38]:
%load_ext IPython


The IPython module is not an IPython extension.


In [40]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
%time
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A.float().T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

CPU times: total: 0 ns
Wall time: 0 ns
Input shape: torch.Size([3, 2])

Output:
tensor([[ 3.4106,  2.5283,  0.7568,  1.2170, -0.9066,  1.2485],
        [ 4.5382,  3.0122,  0.7445,  1.2880, -0.8020,  1.9955],
        [ 5.6657,  3.4961,  0.7323,  1.3590, -0.6974,  2.7424]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [49]:
torch.matmul(torch.rand(6,7), torch.rand(7,8)).shape

torch.Size([6, 8])

In [51]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
x.min(), x.max(), x.type(torch.float32).mean(), x.sum()
print(x.min())

tensor(0)


In [57]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.argmin()

tensor(0)

In [65]:
tensor = torch.arange(0, 100, 10)
torch.rand(2,3)

tensor([[0.4234, 0.6038, 0.1525],
        [0.3970, 0.8703, 0.7563]])

In [73]:
ten16 = tensor.type(torch.float32)
ten16.dtype

torch.float32

In [19]:
demo = torch.rand(4,6)
demo

tensor([[0.4469, 0.9867, 0.2870, 0.7370, 0.8881, 0.5205],
        [0.0839, 0.5927, 0.3416, 0.7209, 0.3817, 0.7357],
        [0.9670, 0.2306, 0.5438, 0.7328, 0.3927, 0.2776],
        [0.5106, 0.2068, 0.9165, 0.7791, 0.2880, 0.0222]])

In [20]:
demo = torch.reshape(demo, (8,3)) 
demo.shape

torch.Size([8, 3])

In [21]:
demo.shape

torch.Size([8, 3])

In [23]:
demo.view(3,8)

tensor([[0.4469, 0.9867, 0.2870, 0.7370, 0.8881, 0.5205, 0.0839, 0.5927],
        [0.3416, 0.7209, 0.3817, 0.7357, 0.9670, 0.2306, 0.5438, 0.7328],
        [0.3927, 0.2776, 0.5106, 0.2068, 0.9165, 0.7791, 0.2880, 0.0222]])