In [17]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Laptop GPU


In [47]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [53]:
# Add and reassign
tensor = tensor + 10
tensor + 10, tensor * 10

(tensor([51, 52, 53]), tensor([410, 420, 430]))

`tensor` returns a tensor , `tensor * 10` returns a tensor, but the both are assigned back into tensor variable as a tuple

It calculates tensor (which results in a tensor).
It calculates tensor * 10 (which also results in a tensor).
It then combines the results of these two calculations into a tuple (result_of_add, result_of_multiply).
Finally, it assigns this tuple back to the variable tensor.

In [54]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([410, 420, 430])