<a href="https://colab.research.google.com/github/HimanshuBijja/pytorch/blob/main/01-fundamentals/exercise01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [51]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [52]:
# Count number of devices
torch.cuda.device_count()

1

In [53]:
tensor = torch.rand(2,3)
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]]) cpu


tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0')

In [54]:
tensor.cpu().numpy()

array([[0.4962566 , 0.7682218 , 0.08847743],
       [0.13203049, 0.30742282, 0.6340787 ]], dtype=float32)

In [105]:
torch.manual_seed(0)
x = torch.rand(7,7)
y = torch.rand(1,7)

In [110]:
ans = x @ y.T
ans , ans.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [111]:
ans.device

device(type='cpu')

In [117]:
ans_on_gpu = ans.to(device)
ans_on_gpu.device


device(type='cuda', index=0)

In [152]:
torch.cuda.manual_seed(0)
x1 = torch.rand(7,7 , device = device)
y1 = torch.rand(1,7, device = device).to(device)

ans = torch.mm(x1, y1.T)
ans

tensor([[2.0534],
        [2.3578],
        [1.8793],
        [1.6912],
        [2.5042],
        [2.0659],
        [1.9022]], device='cuda:0')

In [208]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device : {device}")

x = torch.rand(2,3).to(device)
y = torch.rand(2,3 ,device=device)
x,y
ans = x @ y.T
ans , ans.shape

device : cuda


(tensor([[0.4733, 0.3815],
         [0.4754, 0.9401]], device='cuda:0'),
 torch.Size([2, 2]))

In [210]:
torch.min(ans) , ans.min(),  torch.max(ans) , ans.max()

(tensor(0.3815, device='cuda:0'),
 tensor(0.3815, device='cuda:0'),
 tensor(0.9401, device='cuda:0'),
 tensor(0.9401, device='cuda:0'))

In [213]:
index_x =   torch.argmin(ans)
index_y =  torch.argmax(ans)
index_x , index_y

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

In [219]:
torch.manual_seed(7)
rand_tensor = torch.rand(1,1,1,10)
squeezed_tensor = rand_tensor.squeeze()

rand_tensor, rand_tensor.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))