<a href="https://colab.research.google.com/github/HimanshuBijja/pytorch/blob/main/01-start/page2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

ModuleNotFoundError: No module named 'torch'

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4,5))
zeros, zeros.dtype

(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 torch.float32)

In [ ]:
arr1 = torch.arange(0, 100, 20)
arr1

tensor([ 0, 20, 40, 60, 80])

In [ ]:
zero_like = torch.zeros_like(input=arr1)
one_like = torch.ones_like(input=arr1)

zero_like, one_like


(tensor([0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1]))

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

NameError: name 'torch' is not defined